multiple tweaks

diff --git a/shell/zshrc b/shell/zshrc
--- a/shell/zshrc
+++ b/shell/zshrc
@@ -10,48 +10,47 @@ export ZSH="$HOME/.oh-my-zsh"
 # See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
 # ZSH_THEME="robbyrussell"
 
-
 SPACESHIP_PROMPT_ADD_NEWLINE=false
 SPACESHIP_PROMPT_SEPARATE_LINE=false
 ZSH_THEME="spaceship"
 # https://denysdovhan.com/spaceship-prompt/docs/Options.html#exit-code-exit_code
 SPACESHIP_PROMPT_ORDER=(
-  time          # Time stampts section
-  user          # Username section
-  dir           # Current directory section
-  host          # Hostname section
-  git           # Git section (git_branch + git_status)
-  # hg            # Mercurial section (hg_branch  + hg_status)
-  # package       # Package version
-  # node          # Node.js section
-  # ruby          # Ruby section
-  # python        # Python section
-  # elm           # Elm section
-  # elixir        # Elixir section
-  # xcode         # Xcode section
-  # swift         # Swift section
-  # golang        # Go section
-  # php           # PHP section
-  # rust          # Rust section
-  # haskell       # Haskell Stack section
-  # java          # Java section
-  # julia         # Julia section
-  # docker        # Docker section
-  # aws           # Amazon Web Services section
-  # gcloud        # Google Cloud Platform section
-  # venv          # virtualenv section
-  # conda         # conda virtualenv section
-  # dotnet        # .NET section
-  # kubectl       # Kubectl context section
-  # terraform     # Terraform workspace section
-  # ibmcloud      # IBM Cloud section
-  # exec_time     # Execution time
-  # async         # Async jobs indicator
-  # line_sep      # Line break
-  # battery       # Battery level and status
-  jobs          # Background jobs indicator
-  exit_code     # Exit code section
-  char          # Prompt character
+   time # Time stampts section
+   user # Username section
+   dir  # Current directory section
+   host # Hostname section
+   git  # Git section (git_branch + git_status)
+   # hg            # Mercurial section (hg_branch  + hg_status)
+   # package       # Package version
+   # node          # Node.js section
+   # ruby          # Ruby section
+   # python        # Python section
+   # elm           # Elm section
+   # elixir        # Elixir section
+   # xcode         # Xcode section
+   # swift         # Swift section
+   # golang        # Go section
+   # php           # PHP section
+   # rust          # Rust section
+   # haskell       # Haskell Stack section
+   # java          # Java section
+   # julia         # Julia section
+   # docker        # Docker section
+   # aws           # Amazon Web Services section
+   # gcloud        # Google Cloud Platform section
+   # venv          # virtualenv section
+   # conda         # conda virtualenv section
+   # dotnet        # .NET section
+   # kubectl       # Kubectl context section
+   # terraform     # Terraform workspace section
+   # ibmcloud      # IBM Cloud section
+   # exec_time     # Execution time
+   # async         # Async jobs indicator
+   # line_sep      # Line break
+   # battery       # Battery level and status
+   jobs      # Background jobs indicator
+   exit_code # Exit code section
+   char      # Prompt character
 )
 SPACESHIP_PROMPT_ASYNC=false
 
@@ -151,52 +150,70 @@ source $ZSH/oh-my-zsh.sh
 # alias zshconfig="mate ~/.zshrc"
 # alias ohmyzsh="mate ~/.oh-my-zsh"
 
-
-[[ -f ~/.bash_aliases ]]  && source ~/.bash_aliases
-[[ -f ~/.secrets ]]  && source ~/.secrets
+[[ -f ~/.bash_aliases ]] && source ~/.bash_aliases
+[[ -f ~/.secrets ]] && source ~/.secrets
 export PATH=~/go/bin:~/.local/bin:$PATH
 export DEFAULT_USER=ianic
 export EDITOR="emacs"
 
 if [[ "$OSTYPE" == "darwin"* ]]; then
-    # set homebrew env variables
-    eval "$(/opt/homebrew/bin/brew shellenv)"
-    # prepend go path to be before homebrew go
-    [ -f /etc/paths.d/go ] && PATH=$(cat /etc/paths.d/go):$PATH || true
+   # set homebrew env variables
+   eval "$(/opt/homebrew/bin/brew shellenv)"
+   # prepend go path to be before homebrew go
+   [ -f /etc/paths.d/go ] && PATH=$(cat /etc/paths.d/go):$PATH || true
 
-    # my aws defaults
-    export AWS_PROFILE=aws1
-    export AWS_REGION=eu-central-1
-    export AWS_PAGER=""
-    # export PATH="$PATH:/Users/ianic/.nsc/bin"
-    #
-    # use homebrew Ruby
-    # By default, binaries installed by gem will be placed into:  /opt/homebrew/lib/ruby/gems/3.1.0/bin
-    #
-    if [[ -d /opt/homebrew/opt/ruby/bin ]]; then
-       export PATH=/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH
-       # For compilers to find ruby you may need to set:
-       export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/ruby/lib"
-       export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/ruby/include"
-    fi
+   # my aws defaults
+   export AWS_PROFILE=aws1
+   export AWS_REGION=eu-central-1
+   export AWS_PAGER=""
+   # export PATH="$PATH:/Users/ianic/.nsc/bin"
+   #
+   # use homebrew Ruby
+   # By default, binaries installed by gem will be placed into:  /opt/homebrew/lib/ruby/gems/3.1.0/bin
+   #
+   if [[ -d /opt/homebrew/opt/ruby/bin ]]; then
+      export PATH=/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH
+      # For compilers to find ruby you may need to set:
+      export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/ruby/lib"
+      export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/ruby/include"
+   fi
 
-    # use curl from homwbrew
-    if [[ -d /opt/homebrew/opt/curl/bin ]]; then
-       export PATH="/opt/homebrew/opt/curl/bin:$PATH"
-       # For compilers to find curl you may need to set:
-       export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/curl/lib"
-       export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/curl/include"
-    fi
+   # use curl from homwbrew
+   if [[ -d /opt/homebrew/opt/curl/bin ]]; then
+      export PATH="/opt/homebrew/opt/curl/bin:$PATH"
+      # For compilers to find curl you may need to set:
+      export LDFLAGS="$LDFLAGS -L/opt/homebrew/opt/curl/lib"
+      export CPPFLAGS="$CPPFLAGS -I/opt/homebrew/opt/curl/include"
+   fi
 fi
 
 if [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    # remove user from prompt on remote machine
-    export SPACESHIP_USER_SHOW=false
-    export SPACESHIP_DIR_PREFIX=
-    #export SPACESHIP_HOST_SHOW=false
+   # remove user from prompt on remote machine
+   export SPACESHIP_USER_SHOW=false
+   export SPACESHIP_DIR_PREFIX=
+   #export SPACESHIP_HOST_SHOW=false
+   export PATH=$PATH:/usr/local/go/bin
 fi
 
-fpath=( ~/.oh-my-zsh/custom/plugins/zig "${fpath[@]}" )
+fpath=(~/.oh-my-zsh/custom/plugins/zig "${fpath[@]}")
 
 # completion to work in d
 setopt completealiases
+
+# connect external terminal with vscode in remote session
+vscode_link_file=$HOME/.local/bin/link_vscode.sh
+if [ -z "$VSCODE_IPC_HOOK_CLI" ]; then
+   # when running in external terminal
+   # echo source $vscode_link_file
+   [[ -f $vscode_link_file ]] && source $vscode_link_file
+else
+   # when running in inetgrated vscode terminal
+   # read env variables and prepare file to source in external terminal
+   echo "export VSCODE_IPC_HOOK_CLI=$VSCODE_IPC_HOOK_CLI" >$vscode_link_file
+   code_bin=${VSCODE_GIT_ASKPASS_NODE/server\/node/"server/bin/remote-cli/code-insiders"}
+   echo "alias e=$code_bin" >>$vscode_link_file
+   chmod +x $vscode_link_file
+   # echo created $vscode_link_file
+
+   alias e=$code_bin
+fi
